name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [bukkit, paper]   # 保留矩阵，方便以后扩展
    steps:
      # 1. 拉代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 装 JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 3. 构建
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -DskipTests

      # 4. 上传产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: YamipaPlugin-${{ matrix.flavor }}
          path: target/YamipaPlugin-*.jar
          retention-days: 7
